import type { ItemStatus } from '@shared/types'

/** Неоновые цвета веток по умолчанию (в духе Watch Dogs). */
export const BRANCH_COLORS = [
  '#8b5cf6', // фиолетовый (как в Obsidian) — по умолчанию
  '#22a7f0', // синий
  '#ef4444', // красный
  '#b5d40f', // лаймовый
  '#f59e0b', // янтарный
  '#10b981', // изумрудный
  '#ec4899', // розовый
  '#06b6d4' // циан
]

export function statusOpacity(status: ItemStatus): number {
  switch (status) {
    case 'locked':
      return 0.28
    case 'available':
      return 0.6
    case 'in_progress':
      return 0.85
    case 'done':
      return 1
  }
}

/** Иконки узлов по умолчанию — валидные имена из lucide-react. */
export const NODE_ICONS = [
  // техника/разработка
  'Cpu',
  'Code',
  'Terminal',
  'Database',
  'Cloud',
  'Binary',
  'FileCode',
  'FileCode2',
  'Braces',
  'GitBranch',
  'GitCommit',
  'GitMerge',
  'GitPullRequest',
  'Server',
  'Network',
  'Wifi',
  'Bluetooth',
  'Smartphone',
  'Laptop',
  'Monitor',
  'Keyboard',
  'Mouse',
  'HardDrive',
  'MemoryStick',
  'ShieldCheck',
  'Shield',
  'Lock',
  'KeyRound',
  'Bug',
  'TestTube',
  'TestTube2',
  'FlaskConical',
  // наука
  'Atom',
  'Dna',
  'Microscope',
  'Telescope',
  'Orbit',
  'Satellite',
  'Sigma',
  'Calculator',
  'FunctionSquare',
  'Infinity',
  'PieChart',
  'BarChart',
  'BarChart2',
  'BarChart3',
  'TrendingUp',
  'TrendingDown',
  'LineChart',
  // бизнес/финансы
  'Coins',
  'Banknote',
  'CreditCard',
  'PiggyBank',
  'Landmark',
  'Briefcase',
  'Building',
  'Building2',
  'Store',
  'ShoppingCart',
  'ShoppingBag',
  'Package',
  'Truck',
  'Ship',
  'Anchor',
  'Wallet',
  // природа/спорт на открытом воздухе
  'Compass',
  'Map',
  'MapPin',
  'Mountain',
  'TreePine',
  'Trees',
  'Leaf',
  'Flower',
  'Flower2',
  'Sprout',
  'Sun',
  'Moon',
  'CloudRain',
  'Snowflake',
  'Wind',
  'Droplet',
  'Waves',
  'Fish',
  'Bird',
  'PawPrint',
  'Dog',
  'Cat',
  'Bike',
  'Car',
  'Plane',
  'TrainFront',
  'Bus',
  'Sailboat',
  'Tent',
  'Backpack',
  'Luggage',
  'Umbrella',
  'Palmtree',
  // творчество/письмо
  'Palette',
  'PenTool',
  'Camera',
  'Film',
  'Paintbrush',
  'Paintbrush2',
  'Brush',
  'Pencil',
  'PencilRuler',
  'Ruler',
  'Scissors',
  'Feather',
  'BookMarked',
  'Book',
  'BookOpen',
  'BookOpenCheck',
  'NotebookPen',
  'NotebookText',
  'Newspaper',
  'Library',
  'School',
  'GraduationCap',
  'Languages',
  // музыка/медиа/соцсети
  'Music',
  'Mic',
  'Mic2',
  'Podcast',
  'Radio',
  'Headphones',
  'Guitar',
  'Piano',
  'Drum',
  'Speaker',
  'Video',
  'Clapperboard',
  'Tv',
  'Youtube',
  'Instagram',
  'Twitter',
  'Facebook',
  'Linkedin',
  'Github',
  'Chrome',
  'Figma',
  'Slack',
  'Twitch',
  'Users',
  'User',
  'MessageCircle',
  'MessageSquare',
  // еда
  'Utensils',
  'UtensilsCrossed',
  'ChefHat',
  'CookingPot',
  'Soup',
  'Coffee',
  'Wine',
  'Beer',
  'Pizza',
  'Apple',
  'Salad',
  'IceCreamCone',
  'Cake',
  'Croissant',
  // здоровье/игры/достижения
  'HeartPulse',
  'Activity',
  'HeartHandshake',
  'Stethoscope',
  'Pill',
  'Syringe',
  'BicepsFlexed',
  'Footprints',
  'Dumbbell',
  'PersonStanding',
  'Swords',
  'Award',
  'Medal',
  'Crown',
  'Trophy',
  'Sparkles',
  'Puzzle',
  'Dices',
  'Joystick',
  'Gamepad2',
  'Brain',
  // инструменты/дом
  'Hammer',
  'Drill',
  'Wrench',
  'Cog',
  'Settings',
  'Settings2',
  'Scale',
  'Home',
  'Factory',
  'Warehouse',
  'Castle',
  // время/структура
  'Timer',
  'Clock',
  'AlarmClock',
  'CalendarDays',
  'CalendarCheck',
  'History',
  'Hourglass',
  'Repeat',
  'Shuffle',
  'Layers',
  'LayoutGrid',
  'Boxes',
  'Box',
  'Component',
  'Blocks',
  'Workflow',
  'Rocket',
  'Zap',
  'Target',
  'Flame',
  'Globe',
  'Lightbulb',
  'Star'
]
